schema: ./internal/graphql/schema/schema.graphql
extensions:
  endpoints:
    Local GraphQL Endpoint:
      url: http://localhost:16761/api
      introspect: false
    xAPI Node A:
      url: https://xapi-nodea.fantom.network/
      introspect: false
    Sonic xAPI:
      url: https://xapi.sonic.soniclabs.com/
      introspect: false
